### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by colindaven** [gtamazian/chromosomer#11] opened 2016-11-11 10:15 UTC
Hi,

I too  have a question about the docs. Do you recommend a particular aligner ? 

Which settings should be used ?

If a simple example could just be displayed in the Readme this would be very convenient, I don't think an entire website is really necessary for my purposes.

Thanks,
Colin

**Comment by gtamazian** [comment] 2016-11-30 14:05
Hi Colin,

Sorry for my late reply. I would advise to start with the **blastn** aligner from NCBI BLAST+ package. You may try the following **blastn** options for aligning genome fragments to reference chromosomes:
```
-evalue 0.00001 -perc_identity 80 -max_hsps 2
```

Regards,
Gaik

**Comment by colindaven** [comment] 2016-12-01 12:26
Thanks Gaik. Should I use the default outfmt type then ?

this is the trial command from my perl script. 
`/home/bioinformatics/NAS01/programs/ncbi-blast-2.2.31+/bin/blastn -db Zea_mays.AGPv4.dna.fa  -query $input -evalue 0.00001 -perc_identity 80 -max_hsps 2 -num_threads $threads $output31`;

Thanks,
Colin

**Comment by gtamazian** [comment] 2016-12-01 12:36
Colin, you should specify the BLAST tabular output format for **blastn** results:
```
-outfmt 6
```
Also I would advise to mask genome fragments and reference genome chromosomes to exclude alignments caused by repetitive genome regions. You may use **RepeatMasker**, **WindowMasker** and **DustMasker** tools for that purpose.

**Comment by colindaven** [comment] 2016-12-08 13:53
Thanks. I have now done the alignment and found the help for the fragmentmap command. This helps a lot!

usage: chromosomer fragmentmap [-h] [-r RATIO_THRESHOLD] [-s]
                               alignment_file gap_size fragment_lengths
                               output_map

Construct a fragment map from fragment alignments to reference chromosomes.

positional arguments:
  alignment_file        a BLAST tabular file of fragment alignments to
                        reference chromosomes
  gap_size              a size of a gap inserted between mapped fragments
  fragment_lengths      a file containing lengths of fragment sequences; it
                        can be obtained using the 'chromosomer fastalength'
                        tool
  output_map            an output fragment map file name

optional arguments:
  -h, --help            show this help message and exit
  -r RATIO_THRESHOLD, --ratio_threshold RATIO_THRESHOLD
                        the least ratio of two greatest fragment alignment
                        scores to determine the fragment placed to a reference
                        genome (default: 1.2)
  -s, --shrink_gaps     shrink large interfragment gaps to the specified size
                        (default: False)

**Comment by colindaven** [comment] 2016-12-08 15:38
So, it worked, great. Thanks for this. I'll have a look at comparing the scaffolds of my genotype and the original reference genome using dotplots.

**Comment by nsmackler** [comment] 2017-05-09 11:21
Hi @colindaven, would you be able to share your code for running chromosomer? I've been having trouble getting it to run and have not heard back from the developer either via email or github.
Thanks!

**Comment by colindaven** [comment] 2017-05-09 12:35
Hey, I don't really have any code for this. But I did this:

Ran blastn from the blast+ package as above from contigs against the repeat masked reference genome, but with the --outfmt 6 for compatibility.

Have you done this ?

I then used 
`chromosomer fragmentlength
`
to get the needed frag length file.

Then I believe I just ran the 
`chromosomer fragmentmap
`
command. 

However it has been a while, and I did not get a chance to use the results extensively.

Colin

**Comment by nsmackler** [comment] 2017-05-09 15:26
Thanks, @colindaven. I haven't tried the blastn bit yet, but will do that and get back to you. I guess my main concern right now is making sure I am running the chromosomer commands properly. I installed it using pip, but then have run into errors running it through python
> python
>>>import chromosomer
Then I try and run chromosomer in python, but I don't think it is working. For instance, I can't get the help file to print when I type:
>>> chromosomer fragmentlength -h 

Do you run it directly through bash/unix? Or is it through python? 

Any help here would be much appreciated. If I can get the program running then I'll be happy. The developer hasn't been that responsive. 

Thanks

**Comment by colindaven** [comment] 2017-05-10 06:38
It is written in python, but these are executables or binaries. I.e. run them via the linux bash shell. You don't need to use the python interpreter.

**Comment by nsmackler** [comment] 2017-05-10 12:04
@colindaven Thanks for letting me know. After installing via pip I can't seem to find the executables, so I guess I'm having some trouble at the most basic level... Any advice?

**Comment by gtamazian** [comment] 2017-05-10 12:07
@nsmackler Please try to launch the `chromosomer` command from the command-line interface.

**Comment by nsmackler** [comment] 2017-05-10 15:13
I was able to figure out the installation and now can work the executable. Thanks for your help!

**Comment by gtamazian** [comment] 2017-05-10 22:29
A brief note before closing the issue: one can install Chromosomer without `sudo` by passing the `--user` option to `pip`:

```
pip install --user chromosomer
``` 

In that case, the executable file of Chromosomer will be located in a user's local directory, usually `~/.local/bin`.

**Closed by gtamazian** 2017-05-10 22:29 UTC
